### ISSUE TITLE
Bug: Fix resizing of grid divs when browser is resized

### ISSUE THREAD

**Issue by n-stha** [Aayushstha03/etch-a-sketch#2]
The canvas and the divs(pixels) within it resize when the browser is resized which is not the expected behavior as they should remain static.

Steps to reproduce:
Resize Browser

![Screenshot 2024-02-13 at 16-54-36 Etch-A-Sketch](https://github.com/Aayushstha03/etch-a-sketch/assets/159152983/8bba2b09-26fa-4c5b-b8f1-3a32c3084884)

**Comment by Aayushstha03** [comment]
fixed 👍
